import { db } from '@/lib/db'

async function seed() {
  console.log('Seeding database...')

  // Clear existing products
  await db.product.deleteMany()

  const products = [
    {
      name: 'Mirtilos Frescos',
      nameEn: 'Fresh Blueberries',
      slug: 'mirtilos-frescos',
      description: 'Mirtilos cultivados com cuidado na nossa exploração em Sátão. Com um sabor doce e intenso, ricos em antioxidantes e vitaminas. Perfeitos para consumo direto, smoothies, sobremesas ou acompanhar iogurtes e cereais.',
      descriptionEn: 'Blueberries carefully grown on our farm in Sátão. Sweet and intense flavor, rich in antioxidants and vitamins. Perfect for direct consumption, smoothies, desserts or paired with yogurts and cereals.',
      price: 8.90,
      unit: 'kg',
      category: 'bagas',
      format: 'fresco',
      image: '/images/mirtilos.png',
      inStock: true,
      isSeasonal: true,
      seasonStart: 'Maio',
      seasonEnd: 'Setembro',
      origin: 'Sátão, Viseu',
      nutritionalInfo: 'Por 100g: Calorias 57kcal | Proteínas 0.7g | Hidratos 14.5g | Fibras 2.4g | Vitamina C 9.7mg | Vitamina K 19.3μg',
      storageTips: 'Conservar no frigorífico entre 0-4°C. Lavar apenas antes de consumir. Consumir dentro de 5-7 dias após compra. Pode congelar para conservação prolongada.',
      storageTipsEn: 'Store in refrigerator between 0-4°C. Wash only before consuming. Consume within 5-7 days of purchase. Can be frozen for extended preservation.',
      isFeatured: true,
      order: 1,
    },
    {
      name: 'Framboesas Frescas',
      nameEn: 'Fresh Raspberries',
      slug: 'framboesas-frescas',
      description: 'Framboesas de produção própria, colhidas no ponto ideal de maturação. Sabor delicado e aromático, com a textura suave que nos remete para o melhor da natureza. Ideais para sobremesas, saladas ou simplesmente como snack saudável.',
      descriptionEn: 'Raspberries from our own production, harvested at the ideal ripeness. Delicate and aromatic flavor, with a soft texture that brings the best of nature. Ideal for desserts, salads or simply as a healthy snack.',
      price: 10.50,
      unit: 'kg',
      category: 'bagas',
      format: 'fresco',
      image: '/images/framboesas.png',
      inStock: true,
      isSeasonal: true,
      seasonStart: 'Maio',
      seasonEnd: 'Outubro',
      origin: 'Sátão, Viseu',
      nutritionalInfo: 'Por 100g: Calorias 52kcal | Proteínas 1.2g | Hidratos 11.9g | Fibras 6.5g | Vitamina C 26.2mg | Manganés 0.67mg',
      storageTips: 'Conservar no frigorífico, preferencialmente numa única camada. São muito perecíveis - consumir em 2-3 dias. Não lavar até o momento de consumir.',
      storageTipsEn: 'Refrigerate, preferably in a single layer. Very perishable - consume within 2-3 days. Do not wash until ready to consume.',
      isFeatured: true,
      order: 2,
    },
    {
      name: 'Amoras Frescas',
      nameEn: 'Fresh Blackberries',
      slug: 'amoras-frescas',
      description: 'Amoras silvestres cultivadas com acompanhamento técnico rigoroso. O seu sabor intenso e levemente ácido torna-as versáteis na cozinha: desde compotas e tartes até acompanhamentos para pratos salgados.',
      descriptionEn: 'Wild blackberries cultivated with rigorous technical monitoring. Their intense and slightly tart flavor makes them versatile in the kitchen: from jams and tarts to accompaniments for savory dishes.',
      price: 9.50,
      unit: 'kg',
      category: 'bagas',
      format: 'fresco',
      image: '/images/amoras.png',
      inStock: true,
      isSeasonal: true,
      seasonStart: 'Junho',
      seasonEnd: 'Setembro',
      origin: 'Sátão, Viseu',
      nutritionalInfo: 'Por 100g: Calorias 43kcal | Proteínas 1.4g | Hidratos 9.6g | Fibras 5.3g | Vitamina C 21mg | Vitamina K 19.8μg',
      storageTips: 'Conservar no frigorífico entre 0-4°C. Escolher frutos firmes e de cor escura uniforme. Consumir em 3-5 dias. Excelentes para congelar.',
      storageTipsEn: 'Store in refrigerator between 0-4°C. Choose firm fruits with uniform dark color. Consume within 3-5 days. Excellent for freezing.',
      isFeatured: true,
      order: 3,
    },
    {
      name: 'Groselhas Frescas',
      nameEn: 'Fresh Currants',
      slug: 'groselhas-frescas',
      description: 'Groselhas vermelhas de produção própria, com o seu característico sabor ácido e refrescante. Excelentes para geleias, sumos naturais, decoração de pratos e como complemento em saladas de fruta.',
      descriptionEn: 'Red currants from our own production, with their characteristic tart and refreshing flavor. Excellent for jellies, natural juices, plate decoration and as a complement in fruit salads.',
      price: 11.90,
      unit: 'kg',
      category: 'arbustos',
      format: 'fresco',
      image: '/images/groselhas.png',
      inStock: true,
      isSeasonal: true,
      seasonStart: 'Junho',
      seasonEnd: 'Agosto',
      origin: 'Sátão, Viseu',
      nutritionalInfo: 'Por 100g: Calorias 56kcal | Proteínas 1.4g | Hidratos 13.8g | Fibras 4.3g | Vitamina C 41mg | Ferro 1mg',
      storageTips: 'Conservar no frigorífico. Manter nos ramos até ao consumo. Consumir em 3-5 dias. Ideais para congelar e usar em sumos durante todo o ano.',
      storageTipsEn: 'Refrigerate. Keep on stems until consumption. Consume within 3-5 days. Ideal for freezing and using in juices year-round.',
      isFeatured: false,
      order: 4,
    },
    {
      name: 'Morangos Frescos',
      nameEn: 'Fresh Strawberries',
      slug: 'morangos-frescos',
      description: 'Morangos selecionados da nossa produção, colhidos na perfeição para garantir o máximo de sabor e frescura. Com a doçura e aroma que só os morangos de produção local podem oferecer.',
      descriptionEn: 'Selected strawberries from our production, harvested to perfection to ensure maximum flavor and freshness. With the sweetness and aroma that only locally produced strawberries can offer.',
      price: 6.50,
      unit: 'kg',
      category: 'morangos',
      format: 'fresco',
      image: '/images/morangos.png',
      inStock: true,
      isSeasonal: true,
      seasonStart: 'Março',
      seasonEnd: 'Junho',
      origin: 'Sátão, Viseu',
      nutritionalInfo: 'Por 100g: Calorias 32kcal | Proteínas 0.7g | Hidratos 7.7g | Fibras 2g | Vitamina C 58.8mg | Folato 24μg',
      storageTips: 'Conservar no frigorífico sem retirar o pé verde. Lavar apenas antes de consumir. Consumir em 2-3 dias para máxima frescura. Não congelar com o pé.',
      storageTipsEn: 'Refrigerate without removing the green stem. Wash only before consuming. Consume within 2-3 days for maximum freshness. Do not freeze with the stem.',
      isFeatured: true,
      order: 5,
    },
    {
      name: 'Mirtilos Congelados',
      nameEn: 'Frozen Blueberries',
      slug: 'mirtilos-congelados',
      description: 'Mirtilos congelados individualmente (IQF) logo após a colheça, preservando todas as propriedades nutricionais e o sabor intenso. Disponíveis todo o ano para que possa disfrutar dos benefícios dos mirtilos em qualquer altura.',
      descriptionEn: 'Individually quick-frozen (IQF) blueberries right after harvest, preserving all nutritional properties and intense flavor. Available year-round so you can enjoy the benefits of blueberries anytime.',
      price: 7.50,
      unit: 'kg',
      category: 'bagas',
      format: 'congelado',
      image: '/images/congelados.png',
      inStock: true,
      isSeasonal: false,
      origin: 'Sátão, Viseu',
      nutritionalInfo: 'Por 100g: Calorias 51kcal | Proteínas 0.5g | Hidratos 12.8g | Fibras 2.7g | Vitamina C 7.1mg | Antioxidantes preservados',
      storageTips: 'Manter congelado a -18°C ou inferior. Não descongelar e voltar a congelar. Descongelar apenas a quantidade necessária no frigorífico.',
      storageTipsEn: 'Keep frozen at -18°C or below. Do not refreeze after thawing. Thaw only the needed amount in the refrigerator.',
      isFeatured: false,
      order: 6,
    },
    {
      name: 'Framboesas Congeladas',
      nameEn: 'Frozen Raspberries',
      slug: 'framboesas-congeladas',
      description: 'Framboesas congeladas individualmente (IQF) no pico da maturação. Mantêm toda a cor, aroma e valor nutricional dos frutos frescos. Perfeitas para smoothies, sobremesas e confecção de compotas durante todo o ano.',
      descriptionEn: 'Individually quick-frozen (IQF) raspberries at peak ripeness. They maintain all the color, aroma and nutritional value of fresh fruit. Perfect for smoothies, desserts and making jams year-round.',
      price: 9.00,
      unit: 'kg',
      category: 'bagas',
      format: 'congelado',
      image: '/images/congelados.png',
      inStock: true,
      isSeasonal: false,
      origin: 'Sátão, Viseu',
      nutritionalInfo: 'Por 100g: Calorias 50kcal | Proteínas 1.1g | Hidratos 11.5g | Fibras 6.2g | Vitamina C 24mg | Antioxidantes preservados',
      storageTips: 'Manter congelado a -18°C. Consumir dentro de 12 meses após congelamento. Descongelar gradualmente no frigorífico.',
      storageTipsEn: 'Keep frozen at -18°C. Consume within 12 months of freezing. Thaw gradually in the refrigerator.',
      isFeatured: false,
      order: 7,
    },
    {
      name: 'Cabaz Pequenos Frutos Mistos',
      nameEn: 'Mixed Berry Basket',
      slug: 'cabaz-misto-pequenos-frutos',
      description: 'Cabaz seleção com a melhor combinação dos nossos pequenos frutos da época. Inclui mirtilos, framboesas, amoras e morangos na medida certa para uma experiência única de sabores. Perfeito para presentear ou para se deliciar em família.',
      descriptionEn: 'Selection basket with the best combination of our seasonal small fruits. Includes blueberries, raspberries, blackberries and strawberries in the right measure for a unique flavor experience. Perfect for gifting or family enjoyment.',
      price: 24.90,
      unit: 'unidade',
      category: 'bagas',
      format: 'cabaz-misto',
      image: '/images/cabaz-misto.png',
      inStock: true,
      isSeasonal: true,
      seasonStart: 'Maio',
      seasonEnd: 'Setembro',
      origin: 'Sátão, Viseu',
      nutritionalInfo: 'Composição variável conforme época. Valor nutricional médio por 100g: Calorias 46kcal | Fibras 4.1g | Vitamina C 29mg',
      storageTips: 'Conservar os frutos frescos no frigorífico. Consumir os frutos mais perecíveis primeiro (framboesas e morangos). Cabaz deve ser consumido em 3-5 dias.',
      storageTipsEn: 'Refrigerate fresh fruits. Consume the most perishable fruits first (raspberries and strawberries). Basket should be consumed within 3-5 days.',
      isFeatured: true,
      order: 8,
    },
    {
      name: 'Morangos Congelados',
      nameEn: 'Frozen Strawberries',
      slug: 'morangos-congelados',
      description: 'Morangos congelados individualmente (IQF) no ponto ótimo de doçura. Cortados e prontos a usar, ideais para batidos, sobremesas e confecção de bolos. Disponibilidade todo o ano.',
      descriptionEn: 'Individually quick-frozen (IQF) strawberries at optimal sweetness. Sliced and ready to use, ideal for smoothies, desserts and cake making. Available year-round.',
      price: 5.50,
      unit: 'kg',
      category: 'morangos',
      format: 'congelado',
      image: '/images/morangos.png',
      inStock: true,
      isSeasonal: false,
      origin: 'Sátão, Viseu',
      nutritionalInfo: 'Por 100g: Calorias 30kcal | Proteínas 0.6g | Hidratos 7.2g | Fibras 1.9g | Vitamina C 52mg',
      storageTips: 'Manter congelado a -18°C. Não voltar a congelar após descongelação. Ideal para uso direto em batidos sem descongelar.',
      storageTipsEn: 'Keep frozen at -18°C. Do not refreeze after thawing. Ideal for direct use in smoothies without thawing.',
      isFeatured: false,
      order: 9,
    },
    {
      name: 'Amoras Congeladas',
      nameEn: 'Frozen Blackberries',
      slug: 'amoras-congeladas',
      description: 'Amoras congeladas individualmente (IQF), colhidas no auge da maturação. O processo de congelação rápida preserva o sabor intenso e as propriedades antioxidantes. Versáteis para uso culinário durante todo o ano.',
      descriptionEn: 'Individually quick-frozen (IQF) blackberries, harvested at peak ripeness. The quick-freezing process preserves the intense flavor and antioxidant properties. Versatile for culinary use year-round.',
      price: 8.50,
      unit: 'kg',
      category: 'bagas',
      format: 'congelado',
      image: '/images/amoras.png',
      inStock: true,
      isSeasonal: false,
      origin: 'Sátão, Viseu',
      nutritionalInfo: 'Por 100g: Calorias 42kcal | Proteínas 1.3g | Hidratos 9.4g | Fibras 5.1g | Vitamina C 19mg',
      storageTips: 'Manter congelado a -18°C. Consumir dentro de 12 meses. Descongelar no frigorífico para melhor preservação da textura.',
      storageTipsEn: 'Keep frozen at -18°C. Consume within 12 months. Thaw in refrigerator for best texture preservation.',
      isFeatured: false,
      order: 10,
    },
  ]

  for (const product of products) {
    await db.product.create({ data: product })
  }

  console.log(`Seeded ${products.length} products`)
}

seed()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await db.$disconnect()
  })
